[package]
name = "translator_shexml"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

chumsky = "0.9.3"

vocab = { path = "../vocab/" }
operator = { path = "../operator/" }
plan = { path = "../plan/" }
translator_api = { path = "../translator_api/" }

either.workspace = true
anyhow.workspace = true
uuid.workspace = true
regex.workspace = true
lazy_static.workspace = true
serde_json.workspace = true
serde.workspace = true
clap.workspace = true
log.workspace = true
derive_more.workspace = true
