[package]
name = "translator_shexml"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]

chumsky = "0.9.3"

vocab = { path = "../vocab/" }
operator = { path = "../operator/" }
plan = { path = "../plan/" }
translator_api = { path = "../translator_api/" }

either.workspace = true
serde.workspace = true
log.workspace = true
