test:
  image: rustdocker/rust:stable
  stage: test
  script:
    - cargo test --verbose --jobs 1

build:
  image: rustdocker/rust:stable
  stage: build
  script:
    - apt update
    - apt install -y openjdk-17-jdk nodejs npm
    - ./build.sh

