test:
  image: rustdocker/rust:stable
  stage: test
  script:
    - cargo test --verbose --jobs 1

build:
  image: rustdocker/rust:stable
  stage: build
  script:
    - apt update
    - apt install -y openjdk-17-jdk curl
    - curl -fsSL https://deb.nodesource.com/setup_20.x | sudo bash - 
    - sudo apt-get install -y nodejs
    - ./build.sh

