[profile.release]
opt-level = 3

[workspace]
members = ["crates/*"]
resolver = "3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.6.6"
authors = ["Sitt Min Oo"]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.102"
lazy_static = "1.5.0"
regex = "1.12.3"
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
log4rs = "1.4.0"
log = "0.4.29"
either = "1.15.0"
uuid = { version = "1.23.1", features = ["v4"] }
clap = { version = "4.6.1", features = ["derive"] }
derive_more = { version = "2.1.1", features = [
    "try_unwrap",
    "is_variant",
    "unwrap",
] }
petgraph = { version = "0.8.3", features = ["serde-1", "dot_parser"] }
