[profile.release]
opt-level = 3

[workspace]
members = ["crates/*"]
resolver = "3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.package]
version = "0.6.5"
authors = ["Sitt Min Oo"]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.71"
lazy_static = "1.4.0"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive", "rc"] }
serde_json = "1.0.99"
thiserror = "1.0.44"
log4rs = "1.2.0"
log = "0.4.21"
either = "1.10.0"
uuid = { version = "1.3.0", features = ["v4"] }
clap = { version = "4.3.12", features = ["derive"] }
derive_more = { version = "2.0.1", features = [
    "try_unwrap",
    "is_variant",
    "unwrap",
] }
petgraph = { version = "0.8.3", features = ["serde-1", "dot_parser"] }

