[package]
name = "meamer-rs"
version = "0.1.0"
edition = "2021"


[profile.release]
opt-level = 3

[workspace]
members = ["interpreter", "dataio", "operator", "vocab"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
uuid = { version= "1.3.0", features=["v4"]}
regex = "1.8.4"


[dependencies]
operator = {path = "./operator/"}
interpreter = {path = "./interpreter/"}
csv = "1.2.2"
anyhow = "1.0.71"
clap = {version= "4.3.12", features=["derive"]}
serde_json = "1.0.99"


