[package]
name = "sparql-sat-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
spargebra = "0.4.2"


operator = { path = "../operator/" }
plan = { path = "../plan/" }
translator_normalized_rml = { path = "../translator_normalized_rml/" }
vocab = { path = "../vocab/" }

petgraph.workspace = true
uuid.workspace = true
regex.workspace = true
serde_json.workspace = true
log.workspace = true
