[package]
name = "translator_new_rml"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sophia_api = "0.9.0"
sophia_inmem = "0.9.0"
sophia_turtle = "0.9.0"
sophia_term = "0.9.0"

vocab = { path = "../vocab/" }
operator = { path = "../operator/" }
plan = { path = "../plan/" }
translator_api = { path = "../translator_api/" }


uuid.workspace = true
lazy_static.workspace = true
serde_json.workspace = true
log.workspace = true
derive_more.workspace = true
sophia_isomorphism = "0.9.0"
