[package]
name = "normalizer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
log.workspace = true
oxigraph = { version = "0.5.2", default-features = false }


[dev-dependencies]
anyhow.workspace = true
log4rs.workspace = true
clap.workspace = true

[lib]
name = "normalizer"


[[example]]
name = "cli_normalizer"
