[package]
name = "translator_rml"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
sophia_api = "0.9.0"
sophia_inmem = "0.9.0"
sophia_turtle = "0.9.0"
sophia_term = "0.9.0"

vocab = { path = "../vocab/" }
operator = { path = "../operator/" }
plan = { path = "../plan/" }
translator_api = {path= "../translator_api/"}



either.workspace = true
anyhow.workspace = true
uuid.workspace = true
regex.workspace = true
lazy_static.workspace = true
serde_json.workspace = true
serde.workspace = true
clap.workspace = true
log.workspace = true
derive_more.workspace = true
walkdir = "2.4.0"
